S.A/Models/Flight.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S.A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Det_Ticket = new HashSet<Det_Ticket>();
            this.Flight_Class = new HashSet<Flight_Class>();
            this.Flight_Seats = new HashSet<Flight_Seats>();
            this.Itinerario = new HashSet<Itinerario>();
        }
    
        public int ID_Flight { get; set; }
        public int ID_Passenger { get; set; }
        public int ID_Origin { get; set; }
        public int ID_Destination { get; set; }
        public int ID_FlightStops { get; set; }
        public int ID_Luggage { get; set; }
        public Nullable<int> TotalSeats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Ticket> Det_Ticket { get; set; }
        public virtual Flight_Destination Flight_Destination { get; set; }
        public virtual Flight_Stops Flight_Stops { get; set; }
        public virtual Flight_Luggage Flight_Luggage { get; set; }
        public virtual Flight_Origin Flight_Origin { get; set; }
        public virtual Passenger Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Class> Flight_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Seats> Flight_Seats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerario> Itinerario { get; set; }
    }
}

S.A/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using S.A.Models;

namespace S.A.Controllers
{
    public class FlightsController : Controller
    {
        private StarAllianceEntities1 db = new StarAllianceEntities1();

        // GET: Flights


        
            public ActionResult RegistrarNumeroAsientos()
            {
                return View();
            }

            [HttpPost]
        public ActionResult RegistrarNumeroAsientos(int ID_Flight, int TotalSeats)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=localhost ;Initial Catalog=StarAlliance;Integrated Security=true"))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("RegistrarNumeroAsientos", connection))
                {
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@ID_Flight", ID_Flight);
                    command.Parameters.AddWithValue("@TotalSeats", TotalSeats);
                    command.ExecuteNonQuery();
                }

                // Actualiza el TotalSeats en la base de datos
               
                    var flight = db.Flight.FirstOrDefault(f => f.ID_Flight == ID_Flight);
                    if (flight != null)
                    {
                        flight.TotalSeats = TotalSeats;
                        db.SaveChanges();
                    }
                

                // Coloca el mensaje en ViewBag para mostrarlo en la vista
                ViewBag.Mensaje = "Número de asientos registrado exitosamente.";

                return View();
            }
        }



        public ActionResult ActualizarAsientosReservados()
            {
                return View();
            }


   
            [HttpPost]
        public ActionResult ActualizarAsientosReservados(int ID_Flight)
            {
                // Conexión a la base de datos
                string connectionString = "Data Source=localhost;Initial Catalog=StarAlliance;Integrated Security=true";

                try
                {
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        connection.Open();

                        // Crear el comando para ejecutar el procedimiento almacenado
                        using (SqlCommand command = new SqlCommand("ActualizarAsientosReservados", connection))
                        {
                            command.CommandType = System.Data.CommandType.StoredProcedure;
                            command.Parameters.AddWithValue("@ID_Flight", ID_Flight);

                            // Ejecutar el procedimiento almacenado
                            command.ExecuteNonQuery();
                        }
                    }

                    // Redirigir a la vista que deseas después de ejecutar el procedimiento almacenado
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Manejar cualquier excepción que pueda ocurrir aquí
                    ViewBag.Error = "Ocurrió un error al actualizar los asientos: " + ex.Message;
                    return View();
                }
            }



















    public ActionResult Index()
        {
            var flight = db.Flight.Include(f => f.Flight_Destination).Include(f => f.Flight_Stops).Include(f => f.Flight_Luggage).Include(f => f.Flight_Origin).Include(f => f.Passenger);
            return View(flight.ToList());
        }

        // GET: Flights/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }


        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
   

        public ActionResult InsertarFlight()
        {
            ViewBag.ID_Passenger = new SelectList(db.Passenger, "ID_Passenger", "ID_Passenger");
            ViewBag.ID_Origin = new SelectList(db.Flight_Origin, "ID_Origin", "ID_Origin");
            ViewBag.ID_Destination = new SelectList(db.Flight_Destination, "ID_Destination", "ID_Destination");
            ViewBag.ID_FlightStops = new SelectList(db.Flight_Stops, "ID_FlightStops", "ID_FlightStops");
            ViewBag.ID_Luggage = new SelectList(db.Flight_Luggage, "ID_Luggage", "ID_Luggage");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InsertarFlight(int ID_Passenger, int ID_Origin, int ID_Destination, int ID_FlightStops, int ID_Luggage, int TotalSeats)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=localhost;Initial Catalog=StarAlliance;Integrated Security=true"))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("sp_InsertFlight", connection))
                {
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@ID_Passenger", ID_Passenger);
                    command.Parameters.AddWithValue("@ID_Origin", ID_Origin);
                    command.Parameters.AddWithValue("@ID_Destination", ID_Destination);
                    command.Parameters.AddWithValue("@ID_FlightStops", ID_FlightStops);
                    command.Parameters.AddWithValue("@ID_Luggage", ID_Luggage);
                    command.Parameters.AddWithValue("@TotalSeats", TotalSeats);
                    command.ExecuteNonQuery();
                }
            }

            TempData["Mensaje"] = "Pasajero agregado exitosamente.";

            return RedirectToAction("Index");
        }



        // GET: Flights/Edit/5
        public ActionResult ActualizarFlight(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Destination = new SelectList(db.Flight_Destination, "ID_Destination", "Airport", flight.ID_Destination);
            ViewBag.ID_FlightStops = new SelectList(db.Flight_Stops, "ID_FlightStops", "Airport", flight.ID_FlightStops);
            ViewBag.ID_Luggage = new SelectList(db.Flight_Luggage, "ID_Luggage", "Luggage_Type", flight.ID_Luggage);
            ViewBag.ID_Origin = new SelectList(db.Flight_Origin, "ID_Origin", "Airport", flight.ID_Origin);
            ViewBag.ID_Passenger = new SelectList(db.Passenger, "ID_Passenger", "Fst_Nombre", flight.ID_Passenger);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
      
        public ActionResult ActualizarFlight(int ID_Flight, int ID_Passenger, int ID_Origin, int ID_Destination, int ID_FlightStops, int ID_Luggage, int TotalSeats)
        {
            using (SqlConnection connection = new SqlConnection("Data Source=localhost;Initial Catalog=StarAlliance;Integrated Security=true"))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand("sp_UpdateFlight", connection))
                {
                    command.CommandType = System.Data.CommandType.StoredProcedure;
                    command.Parameters.AddWithValue("@ID_Flight", ID_Flight);
                    command.Parameters.AddWithValue("@ID_Passenger", ID_Passenger);
                    command.Parameters.AddWithValue("@ID_Origin", ID_Origin);
                    command.Parameters.AddWithValue("@ID_Destination", ID_Destination);
                    command.Parameters.AddWithValue("@ID_FlightStops", ID_FlightStops);
                    command.Parameters.AddWithValue("@ID_Luggage", ID_Luggage);
                    command.Parameters.AddWithValue("@TotalSeats", TotalSeats);
                    command.ExecuteNonQuery();
                }
            }

            TempData["Mensaje"] = "Información actualizada correctamente.";

            return RedirectToAction("Mensaje");
        }


        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flight.Find(id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flight flight = db.Flight.Find(id);
            db.Flight.Remove(flight);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

S.A/Views/Flights/ActualizarAsientosReservados.cshtml
@{
	ViewBag.Title = "Actualizar Asientos Reservados";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Actualizar Asientos Reservados</h2>


@using (Html.BeginForm("ActualizarAsientosReservados", "Flights", FormMethod.Post))
{
	<label for="idFlight">ID del Vuelo:</label>
	<input type="number" id="idFlight" name="idFlight" required>
	<br>
	<button type="submit">Actualizar</button>
}

@if (ViewBag.Mensaje != null)
{
	<p>@ViewBag.Mensaje</p>
}

S.A/Views/Flights/ActualizarFlight.cshtml
@model S.A.Models.Flight

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Flight</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Flight)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Passenger, "ID_Passenger", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Passenger", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Passenger, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Origin, "ID_Origin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Origin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Destination, "ID_Destination", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Destination", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_FlightStops, "ID_FlightStops", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_FlightStops", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_FlightStops, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Luggage, "ID_Luggage", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Luggage", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Luggage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ActualizarFlight" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

S.A/Views/Flights/Delete.cshtml
@model S.A.Models.Flight

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TotalSeats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalSeats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Destination.Airport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Destination.Airport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Stops.Airport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Stops.Airport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Luggage.Luggage_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Luggage.Luggage_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Origin.Airport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Origin.Airport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Fst_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Passenger.Fst_Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

S.A/Views/Flights/Details.cshtml
@model S.A.Models.Flight

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TotalSeats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalSeats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Destination.Airport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Destination.Airport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Stops.Airport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Stops.Airport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Luggage.Luggage_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Luggage.Luggage_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flight_Origin.Airport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight_Origin.Airport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Passenger.Fst_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Passenger.Fst_Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_Flight }) |
    @Html.ActionLink("Back to List", "Index")
</p>

S.A/Views/Flights/Index.cshtml
@model IEnumerable<S.A.Models.Flight>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<p>
    @Html.ActionLink("Registrar", "InsertarFlight")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_Flight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Passenger.ID_Passenger)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Flight_Origin.ID_Origin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Flight_Destination.ID_Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Flight_Stops.ID_FlightStops)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalSeats)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID_Flight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Passenger.ID_Passenger)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flight_Origin.ID_Origin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flight_Destination.ID_Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flight_Stops.ID_FlightStops)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalSeats)
        </td>
        <td>
            @Html.ActionLink("Editar", "ActualizarFlight", new { id=item.ID_Flight }) |
      
            @Html.ActionLink("Eliminar", "Delete", new { id=item.ID_Flight })
        </td>
    </tr>
}

</table>

S.A/Views/Flights/InsertarFlight.cshtml
@model S.A.Models.Flight

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Flight</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Passenger, "ID_Passenger", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Passenger", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Passenger, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Origin, "ID_Origin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Origin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Destination, "ID_Destination", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Destination", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_FlightStops, "ID_FlightStops", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_FlightStops", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_FlightStops, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Luggage, "ID_Luggage", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Luggage", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Luggage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="InsertarFlight" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

S.A/Views/Flights/RegistrarNumeroAsientos.cshtml
@{
	ViewBag.Title = "Registrar Número de Asientos";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Registrar Número de Asientos</h2>



@using (Html.BeginForm("RegistrarNumeroAsientos", "Flights", FormMethod.Post))
{
	<label for="idFlight">ID del Vuelo:</label>
	<input type="number" id="idFlight" name="idFlight" required>
	<br>
	<label for="totalSeats">Total de Asientos:</label>
	<input type="number" id="totalSeats" name="totalSeats" required>
	<br>
	<button type="submit">Registrar</button>
}

@if (ViewBag.Mensaje != null)
{
	<p>@ViewBag.Mensaje</p>
}